### ISSUE TITLE
Chapter02-MeaningfulNames

### ISSUE THREAD

**Issue by dev-chloe** [SPONGE-JL/CrashLab-CleanCode#6]
[성현(+정렬)] 의미있는 이름

**Comment by SPONGE-JL** [comment]
**초안이 멋지네요 🚀** 잘봤습니다. :D  ㅎㅎ
나중에 같이 논의해보아요.
**주말 늦은 오후에 수고 많으셨습니다!**

**Comment by SPONGE-JL** [comment]
@dev-chloe 님께서 '[2장. 의미있는 이름](https://github.com/SPONGE-JL/CrashLab-CleanCode/wiki/Chapter-02.-Meaningful-Names)'을 정리하신 뒤에 개인 학습 공간의 코드에 대한 리팩토링을 진행해주셨습니다.

2장의 Participant 입장에서 보기에 성과를 얻으신 것 같아서, [리팩토링을 진행하신 commit diff를 예제로 추천](https://github.com/dev-chloe/hangout-react200/commit/729a52ddb7b82ad08f928dc0dd3d376b2ec10401#diff-f43e2a4761df90bc65ba9567e6073e0d9258684fa8d6e916fec8644f265ddfe3)합니다. 👍🏼
